/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.boothby.dealer.vauto_challenge.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VehicleIdsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-12T19:46:30.596Z")



public class VehicleIdsResponse {
  @SerializedName("vehicleIds")
  private List<Integer> vehicleIds = null;

  public VehicleIdsResponse vehicleIds(List<Integer> vehicleIds) {
    this.vehicleIds = vehicleIds;
    return this;
  }

  public VehicleIdsResponse addVehicleIdsItem(Integer vehicleIdsItem) {
    if (this.vehicleIds == null) {
      this.vehicleIds = new ArrayList<Integer>();
    }
    this.vehicleIds.add(vehicleIdsItem);
    return this;
  }

   /**
   * Get vehicleIds
   * @return vehicleIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getVehicleIds() {
    return vehicleIds;
  }

  public void setVehicleIds(List<Integer> vehicleIds) {
    this.vehicleIds = vehicleIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleIdsResponse vehicleIdsResponse = (VehicleIdsResponse) o;
    return Objects.equals(this.vehicleIds, vehicleIdsResponse.vehicleIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vehicleIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleIdsResponse {\n");
    
    sb.append("    vehicleIds: ").append(toIndentedString(vehicleIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

