version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "steve-sam-vehicle-history"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wkkl9hdux5oq"
s3_prefix = "steve-sam-vehicle-history"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
