/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.boothby.dealer.vauto_challenge.client.api.io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Answer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-03T19:12:24.605Z")
public class Answer {
  @SerializedName("dealers")
  private List<DealerAnswer> dealers = null;

  public Answer dealers(List<DealerAnswer> dealers) {
    this.dealers = dealers;
    return this;
  }

  public Answer addDealersItem(DealerAnswer dealersItem) {
    if (this.dealers == null) {
      this.dealers = new ArrayList<DealerAnswer>();
    }
    this.dealers.add(dealersItem);
    return this;
  }

   /**
   * Get dealers
   * @return dealers
  **/
  @ApiModelProperty(value = "")
  public List<DealerAnswer> getDealers() {
    return dealers;
  }

  public void setDealers(List<DealerAnswer> dealers) {
    this.dealers = dealers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Answer answer = (Answer) o;
    return Objects.equals(this.dealers, answer.dealers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dealers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Answer {\n");
    
    sb.append("    dealers: ").append(toIndentedString(dealers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

